### ISSUE TITLE
Build errors in old crate 'sample' which is used by other crates

### ISSUE THREAD

**Issue by ocdy1001** [RustAudio/dasp#161]
Crate `sample = "0.11.0"` does not build.
```
error[E0282]: type annotations needed
  --> /home/cody/.cargo/registry/src/github.com-1ecc6299db9ec823/sample-0.11.0/src/window.rs:73:41
   |
73 |         let v = phase.to_float_sample().to_sample() * PI_2;
   |                                         ^^^^^^^^^ cannot infer type for type parameter `S` declared on the associated function `to_sample`
   |
help: consider specifying the type argument in the method call
   |
73 |         let v = phase.to_float_sample().to_sample::<S>() * PI_2;
   |                                                  ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sample`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Because of this the crate `synth = "0.11.0"` does not build.

**Comment by mitchmindtree** [comment]
Thanks for the issue @ocdy1001. I think this breakage originally occurred after a change to type inference behaviour in the compiler - that is, when it was originally published, `0.11.0` worked fine. The `synth` crate is an old unmaintained crate (I've since updated the repo description and archived it to make this a little more clear) and for other crates still depending on `sample` `0.11.0` I think we can recommend that users switch to the more recent `dasp` crates instead.
